# Generated by Django 5.0.1 on 2024-02-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_crea',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_modifica',
        ),
    ]
